### ISSUE TITLE
Important: Add screenshots for the Hugo theme site

### ISSUE THREAD

**Issue by digitalcraftsman** [karju-dev/airspace-hugo#4]
Please add a thumbnail and a screenshots with the right dimensions to the your theme. Those will be used on the demo site to showcase your theme. You can find the necessary steps in the [README](https://github.com/gohugoio/hugoThemes#media).

Otherwise, the preview looks broken with missing pictures. The same applies to Twitter cards that we shown when your theme gets featured on the official Hugo Twitter account.

**Note at myself:** don't forget to promote this theme on Twitter!

**Comment by jhabdas** [comment]
https://github.com/letsvalidate/api may save you some time @karju-dev. I generated the screenshots for After Dark by hand. Let me know if you need help doing this.
