### ISSUE TITLE
Missing thumbnail and screenshot images for themes.gohugo.io

### ISSUE THREAD

**Issue by anthonyfok** [karju-dev/airspace-hugo#5]
Hi @karju-dev,

Airspace is now listed on https://themes.gohugo.io/ (Hurray!), except it is missing thumbnail and screenshot images, hence it doesn't look very pretty (Uh oh...), see:

* https://themes.gohugo.io/airspace-hugo/
* https://themes.gohugo.io/

Please review the instructions at https://github.com/gohugoio/hugoThemes#media:

> Screenshots are used as preview in the list. Make sure that they have the right dimensions:
> 
> * Thumbnail should be 900×600 in pixels
> * Screenshot should be 1500×1000 in pixels
> * Media must be located in:
>     * _[ThemeDir]_/images/screenshot.png
>     * _[ThemeDir]_/images/tn.png
> Additional media may be provided in that same directory.

Molte grazie!

**Comment by anthonyfok** [comment]
Duplicate of #4: Add screenshots for the Hugo theme site

**Comment by jhabdas** [comment]
Arguably that mascot is the coolest thing I've ever seen.
